name: Run all service tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-user-service:
    name: Test User Service
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./user-service

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run user-service tests
        run: pytest user_test.py

  test-booking-service:
    name: Test Booking Service
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./booking-service

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run booking-service tests
        run: pytest booking-test.py

  test-order-service:
    name: Test Order Service
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./order-service

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run order-service tests
        run: pytest order_test.py
